Release:
  - head-branch:
      - changeset-release/main
Github Config & Actions:
  - changed-files:
      - any-glob-to-any-file: .github/*
'@kda-community/bootstrap-lib':
  - changed-files:
      - any-glob-to-any-file: packages/libs/bootstrap-lib/*
'@kda-community/chainweb-evm-dashboard':
  - changed-files:
      - any-glob-to-any-file: packages/apps/chainweb-evm-dashboard/*
'@kda-community/chainweb-node-client':
  - changed-files:
      - any-glob-to-any-file: packages/libs/chainweb-node-client/*
'@kda-community/chainweb-stream-client':
  - changed-files:
      - any-glob-to-any-file: packages/libs/chainweb-stream-client/*
'@kda-community/chainwebjs':
  - changed-files:
      - any-glob-to-any-file: packages/libs/chainwebjs/*
'@kda-community/client':
  - changed-files:
      - any-glob-to-any-file: packages/libs/client/*
'@kda-community/client-examples':
  - changed-files:
      - any-glob-to-any-file: packages/libs/client-examples/*
'@kda-community/client-utils':
  - changed-files:
      - any-glob-to-any-file: packages/libs/client-utils/*
'@kda-community/cookbook':
  - changed-files:
      - any-glob-to-any-file: packages/tools/cookbook/*
'@kda-community/create-kadena-app':
  - changed-files:
      - any-glob-to-any-file: packages/tools/create-kadena-app/*
'@kda-community/cryptography-utils':
  - changed-files:
      - any-glob-to-any-file: packages/libs/cryptography-utils/*
'@kda-community/dev-wallet':
  - changed-files:
      - any-glob-to-any-file: packages/apps/dev-wallet/*
'@kda-community/dev-wallet-desktop':
  - changed-files:
      - any-glob-to-any-file: packages/apps/dev-wallet-desktop/*
'@kda-community/explorer':
  - changed-files:
      - any-glob-to-any-file: packages/apps/explorer/*
'@kda-community/graph-proxy':
  - changed-files:
      - any-glob-to-any-file: packages/apps/graph-proxy/*
'@kda-community/rwa-demo':
  - changed-files:
      - any-glob-to-any-file: packages/apps/rwa-demo/*
'@kda-community/graph':
  - changed-files:
      - any-glob-to-any-file: packages/apps/graph/*
'@kda-community/hd-wallet':
  - changed-files:
      - any-glob-to-any-file: packages/libs/hd-wallet/*
'@kda-community/js-monorepo':
  - changed-files:
      - any-glob-to-any-file: ./*
'@kda-community/kadena-cli':
  - changed-files:
      - any-glob-to-any-file: packages/tools/kadena-cli/*
'@kda-community/kda-cli':
  - changed-files:
      - any-glob-to-any-file: packages/tools/kda-cli/*
'@kda-community/pactjs':
  - changed-files:
      - any-glob-to-any-file: packages/libs/pactjs/*
'@kda-community/pactjs-cli':
  - changed-files:
      - any-glob-to-any-file: packages/tools/pactjs-cli/*
'@kda-community/pactjs-generator':
  - changed-files:
      - any-glob-to-any-file: packages/libs/pactjs-generator/*
'@kda-community/proof-of-us':
  - changed-files:
      - any-glob-to-any-file: packages/apps/proof-of-us/*
'@kda-community/kode-icons':
  - changed-files:
      - any-glob-to-any-file: packages/libs/kode-icons/*
'@kda-community/kode-ui':
  - changed-files:
      - any-glob-to-any-file: packages/libs/kode-ui/*
'@kda-community/spirekey-example':
  - changed-files:
      - any-glob-to-any-file: packages/apps/spirekey-example/*
'@kda-community/toolbox':
  - changed-files:
      - any-glob-to-any-file: packages/libs/toolbox/*
'@kda-community/tools':
  - changed-files:
      - any-glob-to-any-file: packages/apps/tools/*
'@kda-community/types':
  - changed-files:
      - any-glob-to-any-file: packages/libs/types/*
'@kda-community-dev/e2e-base':
  - changed-files:
      - any-glob-to-any-file: packages/e2e/e2e-base/*
'@kda-community-dev/eslint-config':
  - changed-files:
      - any-glob-to-any-file: packages/tools/eslint-config/*
'@kda-community-dev/eslint-plugin':
  - changed-files:
      - any-glob-to-any-file: packages/tools/eslint-plugin/*
'@kda-community-dev/integration-tests':
  - changed-files:
      - any-glob-to-any-file: packages/tools/integration-tests/*
'@kda-community-dev/lint-package':
  - changed-files:
      - any-glob-to-any-file: packages/tools/lint-package/*
'@kda-community-dev/markdown':
  - changed-files:
      - any-glob-to-any-file: packages/tools/markdown/*
'@kda-community-dev/scripts':
  - changed-files:
      - any-glob-to-any-file: packages/tools/scripts/*
'@kda-community-dev/shared-config':
  - changed-files:
      - any-glob-to-any-file: packages/tools/shared-config/*
e2e-docs:
  - changed-files:
      - any-glob-to-any-file: packages/e2e/e2e-docs/*
e2e-graph:
  - changed-files:
      - any-glob-to-any-file: packages/e2e/e2e-graph/*
e2e-tools:
  - changed-files:
      - any-glob-to-any-file: packages/e2e/e2e-tools/*
e2e-dev-wallet:
  - changed-files:
      - any-glob-to-any-file: packages/e2e/e2e-dev-wallet/*
e2e-rwa-demo:
  - changed-files:
      - any-glob-to-any-file: packages/e2e/e2e-rwa-demo/*
kadena.js:
  - changed-files:
      - any-glob-to-any-file: packages/libs/kadena.js/*
e2e-proof-of-us:
  - changed-files:
      - any-glob-to-any-file: packages/e2e/e2e-proof-of-us/*
'@kda-community/dev-wallet-example':
  - changed-files:
      - any-glob-to-any-file: packages/apps/dev-wallet-example/*
'@kda-community/snap':
  - changed-files:
      - any-glob-to-any-file: packages/libs/snap/*
'@kda-community/wallet-sdk':
  - changed-files:
      - any-glob-to-any-file: packages/libs/wallet-sdk/*
wallet-sdk-example-app:
  - changed-files:
      - any-glob-to-any-file: packages/apps/wallet-sdk-example/*
hw-app-kda-clone:
  - changed-files:
      - any-glob-to-any-file: packages/apps/hw-app-kda-clone/*
'@kda-community/dev-wallet-plugin':
  - changed-files:
      - any-glob-to-any-file: packages/apps/dev-wallet-plugin/*
'@kda-community/chainweaver-pact-console-plugin':
  - changed-files:
      - any-glob-to-any-file: packages/apps/chainweaver-pact-console-plugin/*
'@kda-community/chainweaver-wallet-connect-plugin':
  - changed-files:
      - any-glob-to-any-file: packages/apps/chainweaver-wallet-connect-plugin/*
'@kda-community/wallet-adapter-core':
  - changed-files:
      - any-glob-to-any-file: packages/libs/wallet-adapter-core/*
'@kda-community/wallet-adapter-ecko':
  - changed-files:
      - any-glob-to-any-file: packages/libs/wallet-adapter-ecko/*
'@kda-community/wallet-adapter-react':
  - changed-files:
      - any-glob-to-any-file: packages/libs/wallet-adapter-react/*
wallet-adapter-react-example:
  - changed-files:
      - any-glob-to-any-file: packages/apps/wallet-adapter-react-example/*
'@kda-community/wallet-adapter-chainweaver-legacy':
  - changed-files:
      - any-glob-to-any-file: packages/libs/wallet-adapter-chainweaver-legacy/*
'@kda-community/wallet-adapter-zelcore':
  - changed-files:
      - any-glob-to-any-file: packages/libs/wallet-adapter-zelcore/*
'@kda-community/wallet-adapter-walletconnect':
  - changed-files:
      - any-glob-to-any-file: packages/libs/wallet-adapter-walletconnect/*
'@kda-community/wallet-adapter-chainweaver':
  - changed-files:
      - any-glob-to-any-file: packages/libs/wallet-adapter-chainweaver/*
'@kda-community/wallet-adapter-magic':
  - changed-files:
      - any-glob-to-any-file: packages/libs/wallet-adapter-magic/*
'@kda-community/wallet-adapter-metamask-snap':
  - changed-files:
      - any-glob-to-any-file: packages/libs/wallet-adapter-metamask-snap/*
