name: 'Archive sandbox volume'
inputs:
  test-object:
    description: 'object under test'
    required: true
runs:
  using: 'composite'
  steps:

    - name: Stop the node
      continue-on-error: true
      shell: bash
      run:  kill $(cat "$SANDBOX_RUN/pid")

    - name: Compute file name
      shell: bash
      id: file_name
      run: |
        FILE_NAME=$(echo "${{ inputs.test-object }}" | cut -d '/' -f 2)
        echo "file_name=$FILE_NAME" >> "$GITHUB_OUTPUT"

    - name: Compress Sandbox
      shell: bash
      run: |
        tar czf devnet_sandbox_${{ steps.file_name.outputs.file_name }}.tar.gz \
          -C "${{ env.SANDBOX_RUN }}" .


    - name: Upload Volume
      uses: actions/upload-artifact@v7
      with:
        name: sandbox_volume_${{ steps.file_name.outputs.file_name }}
        archive: false
        path: devnet_sandbox_${{ steps.file_name.outputs.file_name }}.tar.gz
