name: 'Runner setup'
runs:
  using: 'composite'
  steps:
      - uses: pnpm/action-setup@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: 'pnpm'

      - uses: actions/cache@v6
        with:
          path: .turbo
          key: turbo-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml', 'turbo.json') }}

      - name: Prepare missing .bin Directories
        shell: bash
        run: |
          for PACK in packages/*/*
            do mkdir -p "$PACK/node_modules/.bin"
            done

      - name: Install dependencies
        shell: bash
        run: pnpm install
