name: 'Start Kadena Sandbox'

inputs:
  ghc_version:
    default: "9.10.2"
  cabal_version:
    default: "latest"
  cache_version:
    default: "1"
  node_git_ref:
    default: "master"
  mining_client_git_ref:
    default: "master"

runs:
  using: 'composite'
  steps:

    - name: Setup BIN path
      shell: bash
      run: |
        SANDBOX_BIN="$GITHUB_WORKSPACE/.bin"
        mkdir -p $SANDBOX_BIN
        echo "SANDBOX_BIN=$SANDBOX_BIN" >> "$GITHUB_ENV"

    - name: Setting up MPFR (Ubuntu)
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y libgflags-dev liblz4-dev libzstd-dev libsnappy-dev libbz2-dev libmpfr-dev

    - name: Checkout Node Source
      uses: actions/checkout@v7
      with:
        repository: kda-community/chainweb-node
        path: .repos/chainweb-node
        ref: ${{ inputs.node_git_ref }}

    - name: Checkout Mining client Source
      uses: actions/checkout@v7
      with:
        repository: kda-community/chainweb-mining-client
        path: .repos/chainweb-mining-client
        ref: ${{ inputs.mining_client_git_ref }}

    - name: Compute Cache key
      id: compute-cache-key
      shell: bash
      run: |
        SHA_A=$(git -C .repos/chainweb-node rev-parse HEAD)
        SHA_B=$(git -C .repos/chainweb-mining-client  rev-parse HEAD)

        CACHE_KEY=$(printf "%s%s%s%s%s" "$SHA_A" "$SHA_B" "{{inputs.ghc_version}}" "{{inputs.cabal_version}}" "{{inputs.cabal_version}}"  | sha256sum | cut -d' ' -f1)

        echo "cache_key=$CACHE_KEY" >> "$GITHUB_OUTPUT"

    - name: Restore cache
      id: cache-binaries
      uses: actions/cache/restore@v6
      with:
        path: ${{ env.SANDBOX_BIN}}
        key: node-binaries-${{ runner.os }}-${{ steps.compute-cache-key.outputs.cache_key }}

    - name: Set permissions for .ghcup (ubuntu)
      if: steps.cache-binaries.outputs.cache-hit != 'true'
      shell: bash
      run: sudo chown -R $USER /usr/local/.ghcup

    - name: Install GHC and Cabal
      if: steps.cache-binaries.outputs.cache-hit != 'true'
      uses: haskell-actions/setup@v2
      with:
         ghc-version: ${{ inputs.ghc_version }}
         cabal-version: ${{ inputs.cabal_version }}

    - name: Compile Chainweb node
      if: steps.cache-binaries.outputs.cache-hit != 'true'
      working-directory: .repos/chainweb-node
      shell: bash
      run: |
        cabal build chainweb-node
        cp $(cabal list-bin chainweb-node) "$SANDBOX_BIN"
        strip "$SANDBOX_BIN/chainweb-node"

    - name: Compile Mining client
      if: steps.cache-binaries.outputs.cache-hit != 'true'
      working-directory: .repos/chainweb-mining-client
      shell: bash
      run: |
        cabal build chainweb-mining-client
        cp $(cabal list-bin chainweb-mining-client) "$SANDBOX_BIN"
        strip "$SANDBOX_BIN/chainweb-mining-client"

    - name: Save cache
      if: steps.cache-binaries.outputs.cache-hit != 'true'
      uses: actions/cache/save@v6
      with:
        path: ${{ env.SANDBOX_BIN}}
        key: node-binaries-${{ runner.os }}-${{ steps.compute-cache-key.outputs.cache_key }}